<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thng tin ti khon</name>
   <tag></tag>
   <elementGuidId>55fce88e-22bc-4825-8d99-a1e7e27c19f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.account-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Thông tin tài khoản&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3cc30462-8906-418b-9b51-b78c9a3018ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>account-info</value>
      <webElementGuid>f771fc92-283c-4486-9419-1a87b28a7f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin tài khoản</value>
      <webElementGuid>cb9571b6-a447-4d23-b215-16e0500e9469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;user-section&quot;]/div[2]/div[@class=&quot;account-actions&quot;]/button[@class=&quot;account-info&quot;]</value>
      <webElementGuid>52bed4db-10e8-45ef-88af-6a97a89b6372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>8fc81336-e39e-4b73-ae45-d9c4f0ad5430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 028 3811 6666'])[1]/following::button[1]</value>
      <webElementGuid>4cc71ee6-473e-40ad-a3f6-fb6725a00d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng xuất'])[1]/preceding::button[1]</value>
      <webElementGuid>20ff7fde-46fe-4d70-ad5e-350660f4312a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang Chủ'])[1]/preceding::button[2]</value>
      <webElementGuid>a78ae299-e674-42b3-9240-c1004a61dab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thông tin tài khoản']/parent::*</value>
      <webElementGuid>6231fb7c-2843-4d7b-8bed-fac6b5fa9871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>348b545e-3762-4f7c-8a6e-e28bcaf8f010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Thông tin tài khoản' or . = 'Thông tin tài khoản')]</value>
      <webElementGuid>6ad212e2-4921-4339-82a0-12b639b3a5f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
