<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng xut</name>
   <tag></tag>
   <elementGuidId>f5c72fd8-5fbc-4b3b-9bd5-1a83c3fc37d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.logout-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đăng xuất&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fa95be1-314d-411c-bec9-d4e53ae615e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logout-button</value>
      <webElementGuid>6c2f2aaf-348b-41c4-8935-be58b653f1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng xuất</value>
      <webElementGuid>61c91880-1822-4082-80a4-6238341acd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-customer&quot;]/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;user-section&quot;]/div[2]/div[@class=&quot;account-actions&quot;]/button[@class=&quot;logout-button&quot;]</value>
      <webElementGuid>0ab88343-a3f6-46ae-8bf0-5e9da5a91b76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/button[2]</value>
      <webElementGuid>7c48d617-45c6-45d5-89b0-b09daf14db9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin tài khoản'])[1]/following::button[1]</value>
      <webElementGuid>17ba8993-d97d-4cf4-b270-677cbaab8649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang Chủ'])[1]/preceding::button[1]</value>
      <webElementGuid>f3ce319b-60b7-4a6c-a561-b997a5a3a057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về Chúng Tôi'])[1]/preceding::button[1]</value>
      <webElementGuid>abb10824-70d1-454b-a1e9-9c3f63676b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng xuất']/parent::*</value>
      <webElementGuid>db39e101-90de-4612-a300-15f7a491d0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>eea9ced9-cf11-4765-ac05-a6af2d0604bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Đăng xuất' or . = 'Đăng xuất')]</value>
      <webElementGuid>68f7611d-01d3-4c19-9e44-f75ffbd5ef86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
